repos:
-   repo: local
    hooks:
    -   id: wily
        name: wily
        entry: wily build generator/ test/
        verbose: true
        language: python
        additional_dependencies: [wily]

